# Common properties for all applications go in this file
branding:
  restaurantName: PG Clucks
  menuTitle: The Cluckin Menu

menuBootstrap:
  items:
    - name: Classic
      price: 6.50
    - name: Bahn Mi
      price: 8.50

targets:
  scheme: https
