# Common properties for all applications go in this file
branding:
  restaurantName: Frank Underwood is a bad man
  menuTitle: Freddy's Menu

menuBootstrap:
  items:
    - name: Full Rack of Ribs
      price: 20
    - name: 1/2 Rack
      price: 12
    - name: 1 lb wings
      price: 10

targets:
  scheme: https
